### ISSUE TITLE
7z*.dll not added in publish folder

### ISSUE THREAD

**Issue by DomZZ** [3F/7z.Libs#1]
When I use the dotnet publish command 7z*.dll (7z.dll, 7za.dll, 7zxa.dll) are not copied into the publish folder.

**Comment by 3F** [comment]
It can be done by configuring via ItemGroup or using Copy task or 
vsSolutionBuildEvent at runtime or...
Something like,

final nupkg:

```xml
<ItemGroup>
   <_7zLibs Include="$(TargetDir)\*\7z.dll" />
   <None Include="@(_7zLibs)" Pack="true" PackagePath="bin" />
</ItemGroup>
```

or dst publish dir:

```xml
<Target Name="7zLibsPublishDir" AfterTargets="AfterBuild">
   <Copy SourceFiles="@(_7zLibs)" 
DestinationFiles="@(_7zLibs->'$(PublishDir)\%(RecursiveDir)%(Filename)%(Extension)')" 
/>
</Target>
```
etc.

But I recommend improving current targets for .NET here 
https://github.com/3F/7z.Libs/blob/master/7z.Libs.net.targets to fully 
automate the entire 7z.Libs package, not a specific project. I'll try to 
review any PR to release new package as possible

**Comment by 3F** [comment]
[24.8.1+](https://www.nuget.org/packages/7z.Libs/24.8.1) now provides additional options like `NG7zLibsResolvePublish` to resolve the *Publish* target for .NET projects.
The default value is true. https://github.com/3F/7z.Libs/commit/ed242a6f42d0d7ae23c5ce8779909803a3abd50d

Currently applied only for 24.8+
For older 7z, build it like:
```bat
build --target-version X.Y.v
```
or contact https://github.com/3F/7z.Libs

Other updated options:

MSBuild Property / Environment variable | native C/C+ | .NET    | Default value | Description
----------------------------------------|-------------|---------|---------------|------------------
`NG7zLibsCopyToOutput` | ✔ | ✔ | true | To prevent copying into output path, set as **false**
`NG7zLibsDir32bit` | ✔ | ✔ | x86 | Custom folder name for 32-bit modules if NG7zLibsCopyToOutput=true
`NG7zLibsCopyLicense` | ✔ | ✔ | true | Provide .txt licenses along with modules if NG7zLibsCopyToOutput=true
`NG7zLibsResolvePublish` | - | ✔ | true | Resolve the *Publish* target
`NG7zLibsRootPkg` | ✔ | ✔ | - | Root path to the **7z.Libs** package. E.g. path to tools like $(NG7zLibsRootPkg)tools\
`NG7zLibsLimitToPlatform` | ✔ | - | legacy | Limit copying x86/x64 modules to specific platform. Values: legacy, true, false
`NG7zLibsLimitToPlatform` | - | ✔ | false  | Limit copying x86/x64 modules to specific platform. Relies on `PlatformTarget`
